# Change these first
owner: SammySkycrafts # Your GitHub organization or username, where this repository lives
repo: RMUG-Upptime # The name of this repository

sites:
  - name: Main Site
    url: https://www.rmusergroup.net
  - name: Remote Desktop
    url: https://remote.rmusergroup.net
  - name: RMUG Installations
    url: https://installations.rmusergroup.net
  - name: RMUG Files
    url: https://files.rmusergroup.net
  - name: RMUG CRM
    url: https://crm.rmusergroup.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: dev1.rmusergroup.net
  baseUrl: /RMUG-Upptime
  logoUrl: https://www.rmusergroup.net/images/logo-2.png
  name: RM User Group Status
  introTitle: "Live status for RM User Group"
  navbar:
    - title: Home
      href: https://rmusergroup.net
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
